# TMPDIR=/Users/giulianozorzi/tmp  docker-compose up -d
version: '3.5'

services:
  localstack:
    container_name: "aws_ui_mock"
    image: localstack/localstack
    ports:
      - "4567-4599:4567-4599"
      - "8080:8080"
    environment:
      - SERVICES=sts,route53,s3,dynamodb,iam,ec2
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"